name : raw
schema : gz_raw_data
tables :
    - name: raw_gz_product
      description: "following exercices on le Wagon"
      columns:
          - name: products_id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
          - name : purchSE_PRICE
            tests :
                - not_null:
    
    - name: raw_gz_sales
      description: "following exercices on le Wagon"
      columns:
          - name: orders_id
            description: "" 
            tests:
                - not_null

          - name: pdt_id
            description: ""
            tests:
                - not_null 

          - name: revenue
            description: ""
            tests:
                - not_null

          - name: quantity
            description: ""
            tests:
                - not_null

    - name: raw_gz_ship
      description: "following exercices on le Wagon"
      columns:
          - name: orders_id
            description: "" 
            tests:
                - not_null
          - name: shipping_fee
            description: "" 
            tests:
                - not_null             
          - name: shipping_fee_1
            description: "" 
            tests:
                - not_null    
          - name: logCost
            description: "" 
            tests:
                - not_null
          - name: ship_cost
            description: "" 
            tests:
                - not_null                                       